services:
  # rabbit1:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbit1"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "user"
  #     RABBITMQ_DEFAULT_PASS: "password"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "5672:5672"
  #     - "15673:15672"
  #   labels:
  #     NAME: "rabbitmq1"
  web:
    build: .
    command: python worklog/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - rabbit1
    extra_hosts:
      - "host.docker.internal:host-gateway"
