# Generated by Django 4.2.1 on 2023-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('new_head', models.CharField(default='', max_length=2000)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewspaperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('page_num', models.IntegerField(default=0)),
                ('vlocation', models.IntegerField(default=0)),
                ('hlocation', models.IntegerField(default=0)),
                ('heading', models.CharField(default='', max_length=2000)),
                ('description', models.TextField(default='')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='', max_length=500)),
                ('from_ref', models.CharField(default='', max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
