# Generated by Django 4.2.1 on 2023-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
