# Generated by Django 4.2.1 on 2023-05-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved',
            field=models.SmallIntegerField(default=0),
        ),
    ]
