# Generated by Django 4.2 on 2023-04-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('description', models.CharField()),
                ('heading', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
