# Generated by Django 4.2 on 2023-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(),
        ),
    ]
